### ISSUE TITLE
tv folder created as root

### ISSUE THREAD

**Issue by hannonq** [linuxserver/docker-medusa#16]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Host OS: Ubuntu 18.04

I am trying to run this image using docker-compose.
My compose file is as follows:
```
version: '3'
services:
    medusa:
        image: linuxserver/medusa
        hostname: medusa
        container_name: medusa
        volumes:
            - '/${USERDIR}/docker/medusa:/config'
            - '/${USERDIR}/downloads/completed:/downloads'
            - '/${USERDIR}/media/tvshows:/tv'
            - '/${USERDIR}/docker/shared:/shared'
        ports:
            - '9002:8081'
        restart: always
        environment:
            - 'PUID=${PUID}'
            - 'PGID=${PGID}'
            - 'TZ=${TZ}'
```
The PUID and PGID have been set properly to the id of my current user in the host OS and the docker group id, and so have the TZ and USERDIR variables.

After running `docker-compose -f docker-compose.yml up -d`, the container is initiated on port 9002.
But when I try to add a new show on Medusa, I get the error `Thread_0 :: [] Unable to create the folder /tv/The Big Bang Theory, can't add the show`.

Indeed, when I access the container shell I see that the `/tv` is owned by root:

`drwxr-xr-x+   2 root root 4.0K Feb  4 20:00 tv`

while Medusa is being run as user abc, as shown by the `top` output :

```
 PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  200   197 abc      S     399m   2%   1   0% python /app/medusa/start.py --nolaunch --datadir /config
```

For completion, here's the startup log from Medusa:
```
docker logs medusa
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    998
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Unable to find /config/config.ini, all settings will be default!
2019-02-04 20:13:08 INFO     MAIN :: [] Broken providers found: [u'torrent9', u'newpct', u'btdb']
...  
...  
...  
2019-02-04 20:14:34 ERROR    Thread_0 :: [] Unable to create the folder /tv/The Big Bang Theory, can't add the show
```

I don't think it matters at this point, but the /tv volume has been mounted on my home folder, so no fancy stuff here.

Following the example of what is currently being done on [the 30-config file](https://github.com/linuxserver/docker-medusa/blob/master/root/etc/cont-init.d/30-config), if I `chown -R abc:abc /tv` it works as intended. The show is added to my list.

So, finally my question is: should this last chown command be added to the 30-config file? 
If not, what is a better solution?
